### ISSUE TITLE
jest の設定ファイル etc を管轄する repository を作る

### ISSUE THREAD

**Issue by huequica** [node-jeneralize/pkfire#17]
# summary

- 表題の通り
- 今回はただの json とか yaml ではなく TS を吐き出さないといけないのでちょっと面倒かも。

**Comment by huequica** [comment]
https://kulshekhar.github.io/ts-jest/docs/getting-started/installation/#jest-config-file

う～～～んこれ使えなさそうって感じがあるな、いかんな

```bash
 $ npx ts-jest config:init
Need to install the following packages:
  ts-jest
Ok to proceed? (y) y

Jest configuration written to "/home/huequica/sample/jest.config.js".

$ cat jest.config.js
/** @type {import('ts-jest/dist/types').InitialOptionsTsJest} */
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
};
```

**Comment by 54m** [comment]
test

**Comment by huequica** [comment]
- TS なしで使う場合は `jest --init` で設定を生成
- TSありで使う場合はリポジトリ内の `jest.config.ts` をそのままコピーして使う
  - `ts-jest` と `ts-node` と `@types/jest` のインストールが必要かも

**Comment by huequica** [comment]
`npx jest --init` は対話型やってるのでまずいかも。ちょっと変える
