### ISSUE TITLE
npxで動作するか

### ISSUE THREAD

**Issue by NISHI3** [node-jeneralize/pkfire#47]
# summary
* npx経由で動くか検証する

**Comment by huequica** [comment]
軽く調べた感じ package.json に特別な設定は不要、だがパッケージの名前とコマンドの名前が合致してないと無理そう？
pk の場合はすでに取られているのでパッケージ名を変えるとかの処置が必要そう

![image](https://user-images.githubusercontent.com/40014236/171929945-b7e8c1c7-4c4e-4d60-906d-7e47fcf8d7eb.png)

**Comment by huequica** [comment]
ちょっと試したところやっぱそんな感じらしい
npx がローカル環境に存在しないコマンドを叩こうとすると `commandName@latest` でパッケージを引っ張ってこようとするらしい

```bash
$ npx cowthink
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/cowthink - Not found
npm ERR! 404
npm ERR! 404  'cowthink@latest' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by huequica** [comment]
いい加減 project_kicker とかいうクソみたいな命名からちゃんとオシャンティーで unique な命名に変えるタイミングなのかもしれない

**Comment by huequica** [comment]
#50 でpkfire に変更になった。次回の release でもしかしたら npx で出来るようになるかも。

**Comment by huequica** [comment]
@NISHI3 
```bash
$ npx pkfire
```

これで通るはず

**Comment by huequica** [comment]
一応手元の docker コンテナの中で `npx pkfire` したら期待通り動いたので Close します。
